### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

Updates deps.

### CODE REVIEW

**Comment by montezume** [comment]
I think there's a problem with latest beta release of react-intl, I'll check it out

**Comment by emmenko** [comment]
Yeah there are problems with some of its deps not being transpiled.
We have it pinned to beta-14 in app kit as well.

**Comment by montezume** [comment]
beta15 works but anything above that doesn't.

**Comment by emmenko** [comment]
Btw, this is the problem with the `intl-messageformat` dependency, which ships as ESM and they don't want to ship it compiled to CJS :(

https://github.com/formatjs/react-intl/issues/1371#issuecomment-512726524

**Comment by tdeekens** [comment]
Working on this PR to test the bot.

**Comment by tdeekens** [comment]
CleanShot 2019-07-26 at 10 46 08@2x

**Comment by tdeekens** [comment]
CleanShot 2019-07-26 at 10 46 39@2x

**Comment by tdeekens** [comment]
...so the bot so far seems unable to merge if it's only admins being able to merge/push to branches. I contacted the bot's team to see if we can somehow whitelist the bot.

**Comment by emmenko** [comment]
@montezume FYI regarding react-intl: https://github.com/commercetools/merchant-center-application-kit/pull/897

**Pull request merged**
