### PR TITLE
refactor(breaking): remove font-family

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

As discussed, we want to remove the font-family declarations from UI-Kit and to make it the responsibility of the consumer.

I'll aim the PR at `10.0.0` after Percy runs 😄

### CODE REVIEW

**Comment by montezume** [comment]
Ah, this is annoying

https://stackoverflow.com/questions/6080413/input-doesnt-inherit-the-font-from-body

**Comment by montezume** [comment]
Ah I guess we can specify font-family: inherit on these kind of components...

**Comment by jonnybel** [comment]
Hmm, if we don't set a `font-family`, isn't it inherited by default? (from the nearest parent with a font-family setting)

**Comment by montezume** [comment]
@jonnybel yes but not for the element types I posted

**Comment by jonnybel** [comment]
Oh, nvm, I see that is precisely the problem with inputs.

**Comment by montezume** [comment]
Would be nice if Percy disabled itself when PRs aren't pointed at master...

**Pull request merged**
