### PR TITLE
Date inputs with months greater or equal to the 10th month do not highlight and submit.

### PR DESCRIPTION
**Pull request by ddouglasz**
fix issue where date inputs with months greater or equal to the 10th month do not highlight and submit.

**How can I test this?**
Reproducing the issue is a bit tricky. The fastest way to reproduce the issue is to comment out the `minValue` and `maxValue` props of the` <DateInput>` component in `packages/components/inputs/date-input/src/date-input.story.js`.
Go to date-input on your storybook, check to see that values with, for example, 12/12/2022 or any date with month >=10 (Oct, Nov and Dec) do not submit. Checkout to this current work branch to check again that this PR fixes it. 

Fixes: #2261

### CODE REVIEW

**Review by kark — APPROVED** [review]
Thanks, it seems it solves the issue. I still don't get why the bug only appears for month value >= 10.

**Comment by emmenko** [comment]
Wow, thanks for finding the issue. I have no idea how this relates to the bug, but if it works then let's go for it.

A couple of things maybe to avoid this in the future:
* leave a comment of why it needs to be `if-else`
* (if possible) write a test that ensures this behavior is fixed

Thanks

**Review by Rhotimee — APPROVED** [review]
Good catch 💪🏽

**Comment by ddouglasz** [comment]
> Wow, thanks for finding the issue. I have no idea how this relates to the bug, but if it works then let's go for it.
> 
> A couple of things maybe to avoid this in the future:
> 
> * leave a comment of why it needs to be `if-else`
> * (if possible) write a test that ensures this behavior is fixed
> 
> Thanks

Updated here: https://github.com/commercetools/ui-kit/pull/2304/commits/e70016cf7d00dca93d35f7107b9b15084d51dbb7

Thank you.

**Review by emmenko — APPROVED** [review]
Thanks!

**Pull request merged**
