### PR TITLE
refactor(filter and list icon): updated icon content per UX request

### PR DESCRIPTION
**Pull request by nbryant-commercetools**
#### Summary:
Per a UX request, the work here updates the content of the `FilterAndListIcon` icon for better clarity.

#### Solution:
* Updated the filter and list icon's content with the new version requested by UX.

### CODE REVIEW

**Review by stephsprinkle — COMMENTED** [review]
Understanding that Ariana provided the new icon, is it problematic that the icon went from 24px to 16px in width/height?

**Comment by nbryant-commercetools** [comment]
> Understanding that Ariana provided the new icon, is it problematic that the icon went from 24px to 16px in width/height?

I just updated the icon with what was provided, but I'll double check with her on the sizing.

**Review by torihedden — COMMENTED** [review]
LGTM save for the potential sizing discrepancy Stephanie mentioned.

**Comment by emmenko** [comment]
You also need to run `yarn generate-icons`

**Comment by nbryant-commercetools** [comment]
@stephsprinkle,

After speaking with Ariana, she related that the `16px` size she initially had the icon at was unintentional. She provided an updated version of the icon at the expected size, which has been updated in this PR. Thanks for spotting that!

@emmenko,

Thanks, I ran the icon generation script, and the updated version of the icon component is now included in this PR.

**Review by emmenko — APPROVED** [review]

**Review by stephsprinkle — APPROVED** [review]

**Review by tdeekens — APPROVED** [review]

**Pull request merged**
