### PR TITLE
Icon button changes

### PR DESCRIPTION
**Pull request by ddouglasz**
#### Summary

Icon button changes

When disabled:

### CODE REVIEW

**Review by FilPob — APPROVED** [review]

**Comment by CarlosCortizasCT** [comment]
Looks good to me but I wanted to double check with @FilPob about the border being removed in the new theme not only for the `default` button theme but also for the `info` and `primary` ones

**Comment by FilPob** [comment]
@CarlosCortizasCT  didnt even see that the border is there in the old theme :) so yes, no border for `info` and `primary` in the new theme

**Review by chloe0592 — APPROVED** [review]
Thank you @ddouglasz!

**Review by CarlosCortizasCT — APPROVED** [review]
Thanks! 👍

**Pull request merged**
