### PR TITLE
fix(SelectInput): set menu placement to `auto`

### PR DESCRIPTION
**Pull request by kark**

### CODE REVIEW

**Comment by kark** [comment]
@FilPob Would you mind taking a look at this? 🙏
No extra styling has been added.
I haven't personally seen any regressions in the MC.
With PR the select input menu is moved upwards when there's no space below the input.
In [here](https://mc-15303.mc-preview.europe-west1.gcp.escemo.com/almond-40/customers) you can see with some space below.
Screenshot 2023-09-19 at 08 49 51
In [here](https://mc-15303.mc-preview.europe-west1.gcp.escemo.com/almond-40/products/modified) it fixes the reported bug. 
Screenshot 2023-09-19 at 08 50 46

**Comment by emmenko** [comment]
In the link you shared it doesn't open upwards to me 🤔

**Review by emmenko — APPROVED** [review]
💯 Thanks

**Comment by FilPob** [comment]
@kark looks great! Thanks :)

**Pull request merged**
