### PR TITLE
feat: use new icons

### PR DESCRIPTION
**Pull request by kark**
The intention of this PR is to replace currently used icons with the newly chosen ones.

### CODE REVIEW

**Comment by CarlosCortizasCT** [comment]
I've added a change in the Storybook page for icons to visually mark those components that would be deprecated.
This is the commit: 44cc81766e7fc367d3448fe612cb1e4ccd8d01c4

Please let me know what you think about it. 🙏 

Thanks.

cc/ @emmenko, Natalia

**Comment by emmenko** [comment]
Looks good, thanks Carlos!

**Comment by NataliaSclipet** [comment]
@CarlosCortizasCT I checked with Filip, that's all great!! Thanks Carlos

**Comment by CarlosCortizasCT** [comment]
> @CarlosCortizasCT I checked with Filip, that's all great!! Thanks Carlos

Thanks @NataliaSclipet 

Is there anything else missing or are we done with the current icons here?

**Comment by NataliaSclipet** [comment]
> > @CarlosCortizasCT I checked with Filip, that's all great!! Thanks Carlos
> 
> Thanks @NataliaSclipet
> 
> Is there anything else missing or are we done with the current icons here?

We are done with the legacy icons topic, however I need to setup a call with you to talk about some icons that are vey small in the new library. e.g `CaretDownIcon`

**Comment by CarlosCortizasCT** [comment]
@NataliaSclipet I've applied all the adjustments we discussed yesterday so please, whenever you have some time, take another look at the [preview environment](https://ui-dqboecoyi-commercetools.vercel.app/?path=/story/components-icons--all-icons) and let me know if there's anything missing.

Thanks!

**Comment by CarlosCortizasCT** [comment]
I don't know why all new icons had the property `filled` with the fixed value `none` but that was causing issues in components like `CreatableSelectInput` or `Tag`.
I think we should not use that property (previous icons didn't use it) so I removed it from all new icons and they seem to look fine and issues went away.

**Comment by CarlosCortizasCT** [comment]
There's still an issue with the `AngleLeftIcon` since it seems the contents of that SVG are not centered like the rest of the icons. It's moved to the left which creates some inconsistencies (check the `Pagination` component in Percy).

You can see this even in the [Material Symbols page](https://fonts.google.com/icons):
Screenshot 2022-11-17 at 16 35 47

@NataliaSclipet, @FilPob could we have another SVG version with the content centered?

**Comment by NataliaSclipet** [comment]
> There's still an issue with the `AngleLeftIcon` since it seems the contents of that SVG are not centered like the rest of the icons. It's moved to the left which creates some inconsistencies (check the `Pagination` component in Percy).
> 
> You can see this even in the [Material Symbols page](https://fonts.google.com/icons): Screenshot 2022-11-17 at 16 35 47
> 
> @NataliaSclipet, @FilPob could we have another SVG version with the content centered?

I've replaced the SVG version for the `AngleLeftIcon`! The content it's centered now!

**Comment by CarlosCortizasCT** [comment]
@NataliaSclipet I've just updated the `AngleLeftIcon` as well as `InfoIcon` (requested by @FilPob).

I've gone through the visual changes in Percy and I don't find any other issue.

Please have another look when you have some time 🙏

**Review by NataliaSclipet — APPROVED** [review]
All good! Thanks @CarlosCortizasCT

**Review by NataliaSclipet — CHANGES_REQUESTED** [review]
Filip just noticed that the angle down and up are still smaller, I need to check with Filip the right icons and I'll then provide them to you.

**Comment by NataliaSclipet** [comment]
> Filip just noticed that the `AngleUpIcon` and `AngleDownIcon` are still smaller, I need to check with Filip the right icons and I'll then provide them to you.

I updated the `AngleUpIcon` and `AngleDownIcon`  in the google drive folder and will be sending it to you now as well, this should be the final change, besides that it's all good!

**Comment by CarlosCortizasCT** [comment]
> > Filip just noticed that the `AngleUpIcon` and `AngleDownIcon` are still smaller, I need to check with Filip the right icons and I'll then provide them to you.
> 
> @CarlosCortizasCT I updated the `AngleUpIcon` and `AngleDownIcon` in the google drive folder and will be sending it to you now as well, this should be the final change, besides that it's all good!

@NataliaSclipet I updated those two icons. Perhaps you can take a final look and approve the PR if everything is ok.

Thanks 👍

**Review by NataliaSclipet — APPROVED** [review]

**Review by CarlosCortizasCT — APPROVED** [review]
Finally! 🚀

**Pull request merged**
