### PR TITLE
Refactor theme selector in Storybook

### PR DESCRIPTION
**Pull request by CarlosCortizasCT**
#### Summary

Refactor theme selector in Storybook

## Description

We change the theme selector to allow choosing between the current and the new design in all the environments.

### CODE REVIEW

**Review by kark — APPROVED** [review]
🎉

**Review by Rhotimee — APPROVED** [review]
🚀

**Review by emmenko — APPROVED** [review]
💅

**Review by ddouglasz — APPROVED** [review]
🚀

**Pull request merged**
