### PR TITLE
Version 10.0.0

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

Please check the `changelog` for diff.

Just waiting on #926 

Ready for review.

### CODE REVIEW

**Comment by emmenko** [comment]
@montezume can you give us an update on the status of the PR? Is this ready for review? Are there other things missing?

In any case, like I mentioned in the other PR, I would really like if we can provide codemods when we ship this release.

**Comment by montezume** [comment]
@emmenko @jonnybel added codemods to this branch, we just need to update the documentation in the changelog PR to reflect this fact.

From my end it's ready to review, I would like to do the release ASAP so that we can close this and move forward with rich text editor without distractions

**Comment by emmenko** [comment]
> From my end it's ready to review, I would like to do the release ASAP so that we can close this and move forward with rich text editor without distractions

Sure, however if we want to ship v10 we need to first release a new major of appkit as well, which also requires some breaking changes (including uikit). Just so that you are aware of this.

**Comment by emmenko** [comment]
> added codemods to this branch, we just need to update the documentation in the changelog PR to reflect this fact.

Yeah but it's like a "low level" codemod. As a consumer of the uikit, I would just like to run

```
jscodeshift -t transforms/migrate-from-v9-to-v10.js
```

which then runs all the necessary pre-configured codemods for this release.

If we can do that, it would be awesome!

**Comment by montezume** [comment]
I would like to merge this today if there are no major objections.

**Comment by jonnybel** [comment]
Seems to be a good time to do it, since there are no pending PRs or urgent bugs to be addressed at the moment.

**Pull request merged**
