### PR TITLE
chore: update pptr-testing-library

### PR DESCRIPTION
**Pull request by jonnybel**
#### Summary

`pptr-testing-library` version was locked because of https://github.com/testing-library/pptr-testing-library/issues/31
That has been fixed with https://github.com/testing-library/pptr-testing-library/pull/34.

This PR unlocks the version and updates.

<del>EDIT: Actually, we need to wait for the new version with the fix to be released 😅 </del>

### CODE REVIEW

**Comment by jonnybel** [comment]
This is weird, after updating dependencies, the interactive VRT passed, but then I gave it a second run just to make sure it's not flaky and it failed again 😞

**Comment by emmenko** [comment]
Is it only failing for the `RichTextInput` test?

**Comment by jonnybel** [comment]
Yeah, only the interactive test, it's a timeout. I still haven't figured out why.

Sometimes it also times out on the main branch, but it's a lot less frequent.
With this update, it times-out much more frequently (only passed once out of ~10runs) 🤔

**Comment by jonnybel** [comment]
Alright, so this finally seems to work now.

**Pull request merged**
