### PR TITLE
chore(src/components/inputs): Move inputs to packages

### PR DESCRIPTION
**Pull request by mohib0306**
#### Summary

- move the source code of `src/components/inputs` to `packages/components/inputs`

### CODE REVIEW

**Comment by mohib0306** [comment]
The `src/components/inputs/styles.js` was not moved to `packages/components/inputs` since it used heavily in the `src/components/internals` and will be moved along the refactoring (move) of `src/components/internals` to `packages/components/internals`

**Comment by mohib0306** [comment]
Sorry for the previous comment. Just checked again, `src/components/inputs/styles.js` is used only twice in the `src/components/internals` and  I think we can move it to `packages/components/inputs` in this PR if everyone agrees

**Comment by mohib0306** [comment]
Not sure why this fails. I ran it twice and I also ran the ` yarn test:visual` locally and all the tests passes. 🤷‍♂️

**Comment by tdeekens** [comment]
That seems to be something in the GitHub Runner I presume:

```
[percy] created build #3033: https://percy.io/commercetools-GmbH/ui-kit/builds/6063924
    Error: Failed to launch the browser process!
    /github/workspace/node_modules/@percy/agent/node_modules/puppeteer/.local-
    chromium/linux-756035/chrome-linux/chrome: error while loading shared 
    libraries: libXss.so.1: cannot open shared object file: No such file or 
    directory
```

**Pull request merged**
