### PR TITLE
refactor(link): remove `hasUnderline`

### PR DESCRIPTION
**Pull request by adnasa**
#### Summary

- removes `hasUnderline`. 
- link is underlined by default

ref #1737

### CODE REVIEW

**Review by tdeekens — APPROVED** [review]
Links deserve an underline. I like it! <3

**Comment by adnasa** [comment]
I can't approve percy snapshot 😢

**Comment by tdeekens** [comment]
> I can't approve percy snapshot 😢

It looks good and I approved it to unblock you. It's odd though. You're an admin in this house 😕.

CleanShot 2021-03-17 at 14 16 27@2x

**Comment by adnasa** [comment]
yeah.. it's my personal e-mail.. I'll have a look at changing that

**Review by emmenko — APPROVED** [review]

**Comment by adnasa** [comment]
let's go

**Pull request merged**
