### PR TITLE
fix: replace deprecated and broken package jest-plugin-filename

### PR DESCRIPTION
**Pull request by montezume**
Same as https://github.com/commercetools/merchant-center-application-kit/pull/535/

### CODE REVIEW

**Comment by montezume** [comment]
Hm, netlify build failed twice in a row. Not sure why

**Comment by tdeekens** [comment]
Netlify build issues are fixed by nvmrc.

**Comment by montezume** [comment]
@tdeekens yeah I figured after your explanation in the last pr, thanks 😄

**Comment by tdeekens** [comment]
Sorry if that was overly clear 😅😇

**Comment by montezume** [comment]
Still can't publish 😢

**Pull request merged**
