### PR TITLE
FCT 655: Add `ArrowsMinimizeIcon`

### PR DESCRIPTION
**Pull request by ByronDWall**
As requested by @Shecki and @FilPob [here](https://www.figma.com/file/hymZlJ7T3NyHsmo1FrSFoP/New-homepage-UI?type=design&node-id=3267-20745&mode=design&t=O00CmMpyrS9pZh6y-0), this PR adds a new `ArrowsMinimizeIcon` to ui-kit's icon set.

Icon was added as `arrows-minimize.react.svg`, and the react component was generated using the `yarn generate-icons` script.  All changes to `*.tsx` files were made by `svgr` when ran via `yarn generate-icons`.

### CODE REVIEW

**Review by jaikamat — APPROVED** [review]

**Review by FilPob — APPROVED** [review]

**Review by Shecki — APPROVED** [review]

**Comment by CarlosCortizasCT** [comment]
I don't understand the changes in all the icon files as I was expecting just one file to be created.

I tried to generate the icons in the `main` branch and I didn't get any change.
Also, I generated them in this branch and I seem to get a different output than the one committed here.

@ByronDWall could you please share which versions are you using for **yarn** and **node**?

These are mines:
* node: `18.16.0`
* yarn: `3.7.0`

Thanks.

**Comment by ByronDWall** [comment]
@CarlosCortizasCT 

- node `18.15.0`
- yarn `3.7.0`
Screenshot 2024-01-12 at 10 03 49 AM


I will revert and run the script again though

**Comment by ByronDWall** [comment]
@CarlosCortizasCT I have reverted and pushed the result, and am attaching a screen-recording of the process I used to get this result

https://github.com/commercetools/ui-kit/assets/87667330/b461aa82-ecec-4e17-bcb1-4fa3b9fdaf38

**Comment by ByronDWall** [comment]
@CarlosCortizasCT I've now only committed the svg, generated react component, and its export

**Comment by CarlosCortizasCT** [comment]
> @CarlosCortizasCT I've now only committed the svg, generated react component, and its export

@ByronDWall could you please run the `generate-icons` script from the root folder of the repository?

**Comment by CarlosCortizasCT** [comment]
> > @CarlosCortizasCT I've now only committed the svg, generated react component, and its export
> 
> @ByronDWall could you please run the `generate-icons` script from the root folder of the repository?

@chloe0592 @ddouglasz can you also try to generate icons in your computers to check whether you get something similar? 🙏

**Comment by ByronDWall** [comment]
@CarlosCortizasCT I've reverted again and run `yarn generate-icons` from root instead of the icons sub-directory, and pushed the resulting commit.  I believe that has produced the result you are looking for.  Sorry for the confusion.

**Review by CarlosCortizasCT — APPROVED** [review]
Many thanks, Byron 🙇

**Pull request merged**
