### PR TITLE
chore(ci): add kodiak

### PR DESCRIPTION
**Pull request by tdeekens**
#### Summary

This pull request suggests adding kodiak. A nice and working merge bot. This only adds the config. Later we would install the app.

https://github.com/chdsbd/kodiak#prior-art

### CODE REVIEW

**Comment by tdeekens** [comment]
I will merge this and install the app. I hope @montezume is fine with that. The config can be adjusted anyway and he seemed to like the idea of a bit and more automation around these things.

**Comment by montezume** [comment]
Looks cool!

**Comment by montezume** [comment]
So just to confirm, the reason why it isn't working is because [this](https://github.com/chdsbd/kodiak/issues/119)?

**Comment by tdeekens** [comment]
Exactly. I think we have to ask how much we want that rule. obviously nobody external can push I guess. I got a bit confused by the rule but as I understand it, it overlays the contributors.

**Pull request merged**
