### PR TITLE
feat(localized-money-input): support `isReadOnly` prop

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

Adds support for `isReadOnly` prop to `LocalizedMoneyInput`

### CODE REVIEW

**Comment by montezume** [comment]
@tdeekens 

yes https://github.com/commercetools/ui-kit/blob/24e40d1f0ddcef80b1cf98528e366a085caeeda9/src/components/inputs/money-input/money-input.js#L735

**Comment by montezume** [comment]
Sort of confused you think I made the change without ... opening it in storybook and seeing if anything happened 😕

**Comment by tdeekens** [comment]
> Sort of confused you think I made the change without ... opening it in storybook and seeing if anything happened 😕

No not at all. I just came across the PR. Saw no reviewers were assigned. Wasn't sure I wanted to "drive-by" approve and at least wanted to ask something remotely meaningful.

**Comment by montezume** [comment]
@tdeekens yeah, I was waiting until I merged the other PR because I need to rerun Percy on this one

**Comment by tdeekens** [comment]
All in good intentions. Your PR is reviewed within 15 minutes. I just don't want you blocked :)

**Pull request merged**
