### PR TITLE
chore: add diamond icon

### PR DESCRIPTION
**Pull request by jmcreasman**
Adding a new icon needed for [this ticket](https://commercetools.atlassian.net/browse/PANGOLIN-3467)

### CODE REVIEW

**Review by kark — COMMENTED** [review]
Hey @jmcreasman,
Thanks for for submitting the PR!
Overall, the changes look good. However, upon closer inspection of the [the preview link](https://ui-mx8d818oc-commercetools.vercel.app/?path=/story/components-icons--all-icons) it appears that the output doesn't align with our desired outcome.
image
image

The issue stems from the fact that this particular icon is generated differently from others. While our other icons expect the `fill` property to be provided as a `color` prop, this one requires applying `color` to the svg's `stroke` property and setting fill to `none`.

To resolve this, I recommend reaching out to the designers to provide a different SVG file. This way, we can ensure consistency across our icons, where providing only the fill property is expected.
image

Hope this makes sense. Let me know if you have any questions or need further clarification on this matter.

**Comment by jmcreasman** [comment]
> Hey @jmcreasman, Thanks for for submitting the PR! Overall, the changes look good. However, upon closer inspection of the [the preview link](https://ui-mx8d818oc-commercetools.vercel.app/?path=/story/components-icons--all-icons) it appears that the output doesn't align with our desired outcome. image image
> 
> The issue stems from the fact that this particular icon is generated differently from others. While our other icons expect the `fill` attribute value to be provided as a `color` prop, this one requires applying `color` to the svg's `stroke` attribute and setting fill to `none`.
> 
> To resolve this, I recommend reaching out to the designers to provide a different SVG file. This way, we can ensure consistency across our icons, where providing only the fill property is expected. image
> 
> Hope this makes sense. Let me know if you have any questions or need further clarification on this matter.

Thanks @kark I'll do that and let you know when I've swapped in the (hopefully) better one :)

**Comment by FilPob** [comment]
diamond
please try this one :)

**Review by kark — COMMENTED** [review]
@FilPob Thanks 🙏 I briefly checked the new one and it looks like the same issue is still present.
You may very quickly check it [here](https://yqnn.github.io/svg-path-editor/) by pasting the path
```
M1.31905 6.4827H18.6809M8.17243 1L6.34486 6.4827L9.99996 16.9912L13.6551 6.4827L11.8275 1M10.5616 16.7742L18.7478 6.9507C18.8866 6.78421 18.956 6.70096 18.9825 6.60805C19.0058 6.52612 19.0058 6.43929 18.9825 6.35736C18.956 6.26444 18.8866 6.1812 18.7478 6.01471L14.7881 1.26303C14.7075 1.16635 14.6673 1.11801 14.6179 1.08325C14.5741 1.05246 14.5253 1.02959 14.4737 1.01569C14.4153 1 14.3524 1 14.2265 1H5.77347C5.6476 1 5.58468 1 5.52636 1.01569C5.4747 1.02959 5.42587 1.05246 5.38211 1.08325C5.33273 1.11801 5.29244 1.16635 5.21187 1.26303L1.25215 6.01471C1.11341 6.18119 1.04403 6.26444 1.01752 6.35736C0.994159 6.43929 0.994159 6.52612 1.01752 6.60804C1.04403 6.70096 1.11341 6.78421 1.25215 6.9507L9.43844 16.7742C9.63125 17.0057 9.72765 17.1213 9.84315 17.1636C9.9444 17.2006 10.0555 17.2006 10.1569 17.1636C10.2723 17.1213 10.3688 17.0057 10.5616 16.7742Z
```
and then clicking the `fill` checkbox

I think what we're aiming for is an svg similar to the one available [here](https://www.svgrepo.com/svg/92554/diamond) with the path structured as follows:
```
M63.687 18.573 48.783 4.278c-.185-.176-.431-.481-.687-.481H15.904c-.256 0-.502.305-.687.481L.313 18.47c-.374.354-.418.986-.103 1.392.21.27 30.824 39.726 31.052 39.981.102.115.24.222.343.266.276.12.508.13.79.007.103-.045.24-.135.343-.25.015-.017.038-.023.052-.04l31-39.913a1 1 0 0 0-.103-1.339M15.627 6.434l4.995 11.363H3.606zm8.453 11.363L32 6.535l7.92 11.262zm16.64 2L32 54.674l-8.72-34.877zm-6.794-14h12.542l-4.824 10.975zm-11.57 10.975L17.532 5.797h12.542zm-1.137 3.025 8.66 34.638L2.975 19.797zm21.562 0h18.244L34.12 54.435zm.597-2 4.995-11.363 12.02 11.363z
```

**Comment by FilPob** [comment]
diamond

@kark thanks! I must have uploaded a wrong file cause at my end I see the expected icon correctly also in the  svg path editor tool you posted... Please try again with the one attached in this comment... If it's still the same I need to have another look

**Comment by kark** [comment]
> @kark thanks! I must have uploaded a wrong file cause at my end I see the expected icon correctly also in the svg path editor tool you posted... Please try again with the one attached in this comment... If it's still the same I need to have another look

Thanks ❤️
This one works great!

**Review by CarlosCortizasCT — APPROVED** [review]
Thanks! 👍

**Pull request merged**
