### PR TITLE
Introduce a new Github issue type for documentation improvement

### PR DESCRIPTION
**Pull request by ddouglasz**
#### Summary

Introduce a new Github issue type for documentation improvement

## Description

Introduce a new Github issue type for documentation improvement. This change adds a new issue type to the Github issue template for improving documentation. This change aims to streamline the process of suggesting updates to the project's documentation by providing a dedicated template for documentation improvement issues. The new issue type will help maintain consistency in the documentation improvement process and ensure that all necessary information is included when suggesting updates to the project's documentation.

### CODE REVIEW

**Review by ByronDWall — APPROVED** [review]

**Review by stephsprinkle — COMMENTED** [review]
Can we use [Github issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) instead for our issue types?

**Comment by ddouglasz** [comment]
> Can we use [Github issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) instead for our issue types?

@stephsprinkle This looks nice, one of the benefits I see here is enforcing some required fields we would want to collect along with the requests like browser type or OS.
I only have a tiny concern, which I doubt would be an issue: `Note: Issue forms are currently in beta and subject to change.` 
What do you think, maybe everyone else too ?

**Comment by misama-ct** [comment]
> `Note: Issue forms are currently in beta and subject to change.` What do you think, maybe everyone else too ?

This + I'd hate to have one fancy template and 2 plain ones. Especially the bug-template could profit from those inputs as well. What about just getting this PR out and a follow-up task to "fancify" all templates?

**Comment by ddouglasz** [comment]
>What about just getting this PR out and a follow-up task to "fancify" all templates?

Captured my thought completely 💯
Once we agree on how to go, maybe I can do a single PR to handle all three templates.

**Pull request merged**
