### PR TITLE
docs(changelog): for release v6.0.0

### PR DESCRIPTION
**Pull request by emmenko**
Based on this diff: https://github.com/commercetools/ui-kit/compare/v5.0.0...master

### CODE REVIEW

**Comment by montezume** [comment]
I would like to get #387 in as well, and I think we are really close with #339

**Comment by dferber90** [comment]
#389 is ready code-wise as well. It's only missing some reviews.

Whether we should wait for #389 mostly depends on whether we want to do one big upgrade of the MC or two successive smaller ones. I'm fine either way, but I'd rather get #389 in as well.

**Comment by emmenko** [comment]
Cool, let's try to get this out in the next days then! 🚀

**Comment by dferber90** [comment]
Added the #389 stuff now. @montezume is still doing some fixes and then we're ready for the next release.

**Pull request merged**
