### PR TITLE
refactor(field-label): to use emotion styles

### PR DESCRIPTION
**Pull request by emmenko**
That's right, we basically do not need to pass custom styles anymore for the FieldLabel.

### CODE REVIEW

**Comment by emmenko** [comment]
I'll check with Filip if the new spacings are ok

**Comment by montezume** [comment]
Looks like there's a problem here

screen shot 2019-01-23 at 3 20 04 pm

**Comment by montezume** [comment]
A few problems with things stacking when they should not.

**Comment by emmenko** [comment]
Yes I noticed that, I'm on it

**Comment by emmenko** [comment]
FYI: I'll check with Filip about the visual diffs and approve if it's ok like this.

**Comment by emmenko** [comment]
Snapshots have been approved. @montezume anything else left from your side?

**Pull request merged**
