### PR TITLE
chore: setup eslint for typescript, fix lint errors

### PR DESCRIPTION
**Pull request by emmenko**

### CODE REVIEW

**Review by tdeekens — COMMENTED** [review]
Looks good. To you plan to use any TypeScript preset like xo or will continue to pick rules yourself. Couldn't spot anything in the TS conf.

**Comment by emmenko** [comment]
This is the "same" config as we use in appkit. For now I would go for consistency.

If we find a more "zero config" approach, I'm happy to switch over (in both repos).

**Review by tdeekens — APPROVED** [review]

**Comment by tdeekens** [comment]
Sounds good. I had good and bad experiences with xo. At times rules were annoyingly strict, sometimes a great learning and other times silly subjective.

**Review by adnasa — APPROVED** [review]
nice. thanks for doing this <2 (deliberate typo)

**Pull request merged**
