### PR TITLE
feat(spacings.inline): support flex wrap

### LINKED ISSUE #898: `Spacings.Inline` should support `flex-wrap`
#### Summary

The `Spacings.Inline` component should support the flex-wrap property.

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

Sometimes when we want to make things "flex-wrap". IMHO this is a nice addition to this component, which means we can make more UI elements with needing custom css

[more info](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap)
Fixes #898

### CODE REVIEW

**Comment by montezume** [comment]
Now that I think about it, maybe this doesn't make sense.

Take a look at storybook output

Screen Shot 2019-06-27 at 3 31 47 PM

In cases where you wrap, you wouldn't want margin like this, right?

**Comment by emmenko** [comment]
Maybe then you can just use `Grid` if you want elements to wrap, then we don't need `flex-wrap` anymore

**Comment by jonnybel** [comment]
Hmm, yes, the wrapping is not very "compatible" with the margins.

In cases like these I'd rather use a custom styled div.

**Comment by emmenko** [comment]
> In cases like these I'd rather use a custom styled div

Just use css grid 😉

**Pull request closed without merging**
