### PR TITLE
fix(types): avoid using `React.FC` as it does not properly work with `defaultProps`.

### PR DESCRIPTION
**Pull request by emmenko**
I forgot why we weren't using `FC` in appkit. It's because it does not properly work with `defaultProps`.

This PR fixes that.

PS: additionally, I also migrated the `spacings` preset to TS, as otherwise the spacing component types are not available when using the preset.

### CODE REVIEW

**Review by tdeekens — APPROVED** [review]
Maybe ADRs for ui-kit could help to document such decisions?

**Comment by emmenko** [comment]
Yes we should document how to use/write TS components.

**Review by adnasa — APPROVED** [review]
so don't use `React.FC` then? 😆

**Comment by emmenko** [comment]
Yep 🙂

**Pull request merged**
