### PR TITLE
Added `info` color in `SecondaryIconButton` and replaced the `Info.svg`

### PR DESCRIPTION
**Pull request by chloe0592**
As we want to change the `FieldLabel` component style this PR is needed as a first step.

It adds a new color `info` to `SecondaryIconButton` and replaces the old icon `Info.svg` with the new one.

Screenshot 2024-03-21 at 12 26 48

### CODE REVIEW

**Comment by FilPob** [comment]
@chloe0592 thanks, looks all as proposed. However I am not very happy with the hover effect. Could we please add a new color token: `color-info-60` hsl(203,94,60) and use this one for the hover effect? This color also can be included in the old theme.

**Comment by chloe0592** [comment]
> @chloe0592 thanks, looks all as proposed. However I am not very happy with the hover effect. Could we please add a new color token: `color-info-60` hsl(203,94,60) and use this one for the hover effect? This color also can be included in the old theme.

Sure. I changed it here - [ff151ce](https://github.com/commercetools/ui-kit/pull/2755/commits/ff151ce43dbf5d785cc97337cd3cf0e0c62c0a8a). Let me know how it looks to you now.

**Review by FilPob — APPROVED** [review]

**Comment by FilPob** [comment]
perfect :) thanks

**Review by kark — APPROVED** [review]
💯

**Review by CarlosCortizasCT — APPROVED** [review]

**Pull request merged**
