### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by NoobTW**
#### Summary

Add badges for #136.

#### Description

Add badges like:

- npm latest version
- npm minified size
- GitHub issues
- GitHub forks
- GitHub stars
- License

Awesome badges are created from [shields.io](https://shields.io).

### CODE REVIEW

**Comment by montezume** [comment]
Hey! Thanks for the contribution.

Would you mind

* Moving the badges underneath the title and subtitle. Like [here](https://github.com/styled-components/styled-components)
* Aligning 'center' the badges.

My one concern is using the bundle size badge, as we have some sort of issue now with bundlephobia showing the bundle size way smaller than in reality. What say you @commercetools/ui-kit ?

**Comment by tdeekens** [comment]
We can leave them out for now. Let's wait for two days if @NoobTW gets to it otherwise we change the alignment ourselves.

**Comment by NoobTW** [comment]
How about this?

I've also removed the size badge.

**Comment by montezume** [comment]
@NoobTW do you want to update your branch and merge?

**Pull request merged**
